# Generated by Django 6.0.3 on 2026-04-05 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deceased_name', models.CharField(max_length=255)),
                ('deceased_pan', models.CharField(max_length=15)),
                ('death_certificate_no', models.CharField(max_length=100)),
                ('death_certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_aadhaar_last4', models.CharField(max_length=4)),
                ('relation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('fraud_risk_score', models.IntegerField(default=2)),
                ('total_assets_found', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bridge_loan_available', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('situation_label', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('documents_needed', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('time_estimate', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='claims.claimsession')),
            ],
        ),
    ]
