# Generated by Django 6.0.3 on 2026-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimsession_ocr_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
