# Generated by Django 6.0.3 on 2026-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimsession_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='extracted_certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='extracted_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='fraud_risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='verification_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
